version: 2
jobs:
  build:
    docker:
      - image: quay.io/3scale/s2i-openresty-centos7:luarocks-build
        environment:
          TEST_NGINX_BINARY: openresty
      - image: redis:3.2.8-alpine
      - image: docker:17.03.1-ce-dind
    working_directory: /opt/app-root/apicast
    steps:
      - checkout
      - restore_cache:
          keys:
            - apicast-v1-{{ checksum "apicast/apicast-0.1-0.rockspec" }}-apicast-rockspec
            - apicast-v1-{{ .Branch }}
            - apicast-v1-master
      - run: luarocks make apicast/*.rockspec
      - save_cache:
          key: apicast-v1-{{ checksum "apicast/apicast-0.1-0.rockspec" }}-apicast-rockspec
          paths:
            - /usr/local/openresty/luajit/share/lua/5.1
            - /usr/local/openresty/luajit/lib64/luarocks/rocks
            - /usr/local/openresty/luajit/lib/lua/5.1
      - restore_cache:
          keys:
            - apicast-v1-{{ checksum "rockspec" }}-rockspec
            - apicast-v1-{{ .Branch }}
            - apicast-v1-master
      - run: luarocks make rockspec
      - save_cache:
          key: apicast-v1-{{ checksum "rockspec" }}-rockspec
          paths:
            - /usr/local/openresty/luajit/share/lua/5.1
            - /usr/local/openresty/luajit/lib64/luarocks/rocks
            - /usr/local/openresty/luajit/lib/lua/5.1
      - run: make busted
      - run: prove # no carton on centos
      - setup_remote_docker
      - run: make builder-image
      - run: make test-builder-image gateway-logs --keep-going
      - run: make prove-docker
      - run: make runtime-image
      - run: make test-runtime-image gateway-logs --keep-going
      - run: make doc
      # - run: make test-doc # TODO: extract this into a docker container or some node container
      - run: make danger
